apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    type: service
spec:
  ports:
    - port: 80
      targetPort: 5432
  selector:
    name: postgres-app-pod
    app: demo-postgres-app