apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    type: service
spec:
  ports:
    - port: 80
      targetPort: 6379
  selector:
    name: redis-app-pod
    app: demo-redis-app