apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-workker-app
spec:
  containers:
   - name: worker-app-container
     image: kodekloud/examplevotingapp_worker:v1