apiVersion: v1
kind: Service
metadata:
  name: sample-cluster-ip-service
  labels:
    type: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
    type: sample