apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    network: nw-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30008
      targetPort: 80
  selector:
    app: frontend
    type: sample