apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller
  labels:
    name: my-app
    type: sample
spec:
  template:
    metadata:
      name: saurabh-app
      labels:
        type: sample
        app: frontend
    spec:
      containers:
        - name: saurabh-container1
          image: nginx
  replicas: 2